// The actions types of redux reducer for previnfing typing errors
export const CATEGORIES_ACTIONS_TYPES = {
  SET_CATEGORIES_START: "SET_CATEGORIES_START",
  SET_CATEGORIES_SUCCESS: "SET_CATEGORIES_SUCCESS",
  SET_CATEGORIES_FAILED: "SET_CATEGORIES_FAILED",
};
